/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

val SRCDIR="../../src"
val projectVersion: String ="0.3.10"

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:32.1.1-jre")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

sourceSets {
    main {
        java {
            // 外部ディレクトリを追加
            srcDirs(SRCDIR)
        }
    }
}

tasks.getByName<JavaCompile>("compileJava").dependsOn("copyVersion")

tasks.register<Copy>("copyVersion") {
	from("${SRCDIR}/jp/nyatla/tbskmodem")
	into("build/classes/java/jp/nyatla/tbskmodem")
	include("Version.class")
}


// コンパイルとJAR生成の設定
tasks.jar {
    archiveFileName.set("tbskmodem-java.${projectVersion}.jar")
}
